### ISSUE TITLE
Period chaining doesn't go more than one layer deep. 

### ISSUE THREAD

**Issue by seeker25** [gmddmg/NTemplates#3]
For example #S.Clients.Name# would be nice to have. 
I think the work around for this right now would be to bind clients for example to C then use the following:
#C.Name#
But this doesn't really make sense in the usage of say single instances inside of C. 

I'd have to restructure my class and make it so the first level properties accessed second level properties etc. (Cumbersome because i'm using generated classes, that are shared). 

I'm looking into and proposing a way to dig deeper into the instance.

**Comment by gmddmg** [comment]
Correct. The best approach right now would be to restructure the class as you say.  The idea is was note to make NTemplates able to work with any possible structure. Rather, it was designed to work with datatables initially and then I extended it to work with classes provided they have a simple structure (1 level as you noticed)

**Comment by seeker25** [comment]
Ok, i'll take your suggestion and restructure the class. Closing this ticket.

**Comment by gmddmg** [comment]
Wow, looking at the code now I realize I have forgotten how complex it became and how much effort I put on it! The problem here is that although the document creator accepts a list of objects, internally it creates a datatable object. 
I will have to review this from a whole new perspective.   Then... I will see if it´s worth to re open the issue ha ha

**Comment by gmddmg** [comment]
Ok @seeker25  I will create a branch and give it a try, didn´t re open the issue yet :)
